serverAddr = "43.153.104.236"
serverPort = 22524

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

[[proxies]]
name = "myapp-tcp"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5555
remotePort = 6000